### ISSUE TITLE
Setup of platform prismatik is taking longer than 60 seconds. Startup will proceed without waiting any longer.

### ISSUE THREAD

**Issue by FaserF** [zomfg/home-assistant-prismatik#11]
Thank you very much for your addon. Unfortunatly I cant get it to work.
Homeassistant Version: 2020.12.1
Prismatik Version: 6.0.0.104

`Logger: homeassistant.components.light
Source: helpers/entity_platform.py:231
Integration: Licht (documentation, issues)
First occurred: 7:38:06 (1 occurrences)
Last logged: 7:38:06

Setup of platform prismatik is taking longer than 60 seconds. Startup will proceed without waiting any longer.`

Homeassistant Config:
`light:
  - platform: prismatik
    host: 192.168.178.59
    name: "Prismatik"
    profile_name: homeassistant`

**Comment by zomfg** [comment]
Hi
It seems to work for me on a more or less fresh 2020.12.1 and from what I can gather in similar cases it's often due to external causes, like network or weird caching issues in HA.
So for now
- hard reboot HA (so don't do the usual simple "restart" in HA UI)
- make sure you unchecked "Listen only on local interface" in Prismatik, and Prismatik host is reachable from HA (or at least somewhere else from HA's network)

Also form your Prismatik's version I guess you are using the official one, which isn't really maintained these days, I'd recommend to switch to [this one](https://github.com/psieg/Lightpack) (and if you do get [this release](https://github.com/psieg/Lightpack/releases/tag/5.11.2.25), because while investigating your thing I found a bug in the latest one, that should be fixed in the next release)
This wont fix this particular issue, but it's greatly improved compared to the original.

**Comment by FaserF** [comment]
Wow. Thank you so much! The version you have linked is working so much better than the old unofficial I had.
Maybe you could link that anywhere at your readme?

Anyway, it is working now :) Such a great HA Addon!

**Comment by FaserF** [comment]
One question is left for me:
I am unable to set a persistent color via Homeassistant. I can successfully turn Prismatik on/off and I can choose the profile. but if I switch to the "homeassistant" profile and try to set a color, nothing happens and I get an error.

**Comment by zomfg** [comment]
Hmm.. did you get the [5.11.2.25](https://github.com/psieg/Lightpack/releases/tag/5.11.2.25) or the latest (.27 I think)? You'll need the .25 until the next release (so .28+).

I do indeed link to that fork in the readme (bottom), but maybe a more explicit note would be better 😄

**Comment by FaserF** [comment]
I got the 5.11.2.25 release, but as I have just seen it has updated itself to .27 in the background without me noticing. 
Thanks for clearing me out. Than this seems to be the issue
